### ISSUE TITLE
병합 후 작업

### ISSUE THREAD

**Issue by joonyy** [joonyy/Daytodo#17]
# 프론트 파일 마무리 및 css 연결작업
1. date.ejs 파일(구 createTodo.ejs)에 css 연결하기
2. viewTodo 파일 생성하기
3. index.ejs에 tbody overflow 속성 설정하기
4. week.ejs 파일 생성하기

**Comment by dongmyeong930213** [comment]
y = 1,3
~ = 2,4

**Comment by dongmyeong930213** [comment]
1,2,3 = y

~ = 4

**Comment by dongmyeong930213** [comment]
viewtodo.css 수정
